### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [LoryRich/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by LoryRich** [comment]
Lori Roberg
Milwaukee, Wisconsin
Crab Legs
Learning GitHub, Bootstrap, HTML, CSS, Javascript and Jquery. It is taking up all my time.
